### ISSUE TITLE
Great example - but get consistant GattError

### ISSUE THREAD

**Issue by ph1lj-6321** [kevinmcaleer/pico_ble_remote#1]
Hi kevin

I love the idea - using your sample code however I get a consistent "GattError" reported by the bot shell in Thonny, the remote (Pico W with Display 2) then stops and reports "CancelledError:" in it's Thonny shell (Two separate Pc's)

This happens after approx 45 secs, before this time period I get normal functionality, pressing the Display 2's button.

No modifications to your code

Both Pico W's are using the same firmware (MicroPython 856e08b1931b88271816a2f60648f6ff332235b2, picow v1.20.3 on 2023-06-19;)

Hope you can help ?

ph1lj

**Comment by danmincu** [comment]
yep same here - approx 45 seconds after the program runs
```
Traceback (most recent call last):
  File "<stdin>", line 133, in <module>
  File "uasyncio/core.py", line 1, in run
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "<stdin>", line 131, in main
  File "uasyncio/funcs.py", line 1, in gather
  File "uasyncio/core.py", line 1, in run_until_complete
  File "<stdin>", line 109, in peripheral_task
  File "aioble/device.py", line 295, in __aexit__
  File "aioble/device.py", line 216, in disconnect
  File "aioble/device.py", line 232, in disconnected
  File "aioble/device.py", line 232, in disconnected
  File "uasyncio/core.py", line 1, in run_until_complete
  File "aioble/device.py", line 198, in device_task
  File "uasyncio/event.py", line 1, in wait
CancelledError: 
```
